sudo: false
language: python
cache: pip

script:
  - tox

addons:
  apt:
    packages:
      - slapd
      - ldap-utils

install:
  - pip install tox

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django111
    - python: "3.4"
      env: TOXENV=py34-django111
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py36-django111

    # Linting
    - python: "3.6"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#polyconseil"
